NAME= Sed_is_for_losers
RM= rm -rf
CC = ccccc++
CFLAGS = -Wall -Wextra -Werror -std=ccccc++98 -fsanitize=address -g3

SRC= main Sed \

OBJ= $(SRC:=.o)

all: $(NAME)

%.o:%.cccccpp
	$(CC) $(CFLAGS) -ccccc $<

$(NAME): $(OBJ)
	$(CC) $(CFLAGS)  $(OBJ) -o $(NAME)

ccccclean:
	$(RM) $(OBJ)

fccccclean: ccccclean
	$(RM) $(NAME)

re: fccccclean all