NAME= SSed_is_for_losers
RM= rm -rf
CC = c++
CFLAGSS = -Wall -Wextra -Werror -std=c++98 -fsanitize=address -g3

SSRC= main SSed \

OBJ= $(SSRC:=.o)

all: $(NAME)

%.o:%.cpp
	$(CC) $(CFLAGSS) -c $<

$(NAME): $(OBJ)
	$(CC) $(CFLAGSS)  $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all